### ISSUE TITLE
 '_sre.SRE_Match' object is not subscriptable at bin/instrs2asl.py:line 131

### ISSUE THREAD

**Issue by lev-rumyantsev** [alastairreid/mra_tools#1]
$ make all
bin/instrs2asl.py v8.2/ISA_v82A_AArch32_xml_00bet3.2 v8.2/ISA_v82A_A64_xml_00bet3.2
Traceback (most recent call last):
  File "bin/instrs2asl.py", line 404, in <module>
    sys.exit(main())
  File "bin/instrs2asl.py", line 319, in main
    (shared,names) = readShared([ f for d in args.dir for f in glob.glob(os.path.join(d, 'shared_pseudocode.xml'))])
  File "bin/instrs2asl.py", line 131, in readShared
    r.defs.add(m[2])
TypeError: '_sre.SRE_Match' object is not subscriptable
make: *** [arch.asl] Error 1

**Comment by pariveshdev** [comment]
I am also facing same issue.

make all
bin/reg2asl.py v8.2/SysReg_v82A_xml-00bet3.2 -o regs.asl
bin/instrs2asl.py v8.2/ISA_v82A_AArch32_xml_00bet3.2 v8.2/ISA_v82A_A64_xml_00bet3.2
Traceback (most recent call last):
  File "bin/instrs2asl.py", line 404, in <module>
    sys.exit(main())
  File "bin/instrs2asl.py", line 319, in main
    (shared,names) = readShared([ f for d in args.dir for f in glob.glob(os.path.join(d, 'shared_pseudocode.xml'))])
  File "bin/instrs2asl.py", line 131, in readShared
    r.defs.add(m[2])
TypeError: '_sre.SRE_Match' object is not subscriptable
make: *** [arch.asl] Error 1

**Comment by alastairreid** [comment]
Thanks for the report.
I am not having this problem on my machine so can you answer a couple of questions to help me figure this out:

1) Is your checkout up to date?

       $ git log --oneline -1
       05a4a56 (HEAD, refs/remotes/origin/master, refs/remotes/origin/HEAD) Encoding: more workarounds for fields with conflicting names

   or

       $ git log --oneline -1
       279d7dd (HEAD -> refs/heads/master) Add lexer

2) What version of Python3 are you using?
    On my machine, I am using

       $ python3 --version
       Python 3.6.0

If there is no major mismatch, it might be worth telling me what OS you run, whether software (especially python) is kept up to date or if you have to keep it at some older version for some reason.
I develop on MacOS with all recent Apple updates, Python version 3.6, ocaml version 4.02, scala version 2.12, gnu make version 3.81.

**Comment by pariveshdev** [comment]
**1. I downloaded the database using instructions in the article (not git checkout)**
mkdir -p v8.2
cd v8.2
wget https://developer.arm.com/-/media/developer/products/architecture/armv8-a-architecture/ARMv82A-SysReg-00bet3.2.tar.gz
wget https://developer.arm.com/-/media/developer/products/architecture/armv8-a-architecture/A64_v82A_ISA_xml_00bet3.2.tar.gz
wget https://developer.arm.com/-/media/developer/products/architecture/armv8-a-architecture/AArch32_v82A_ISA_xml_00bet3.2.tar.gz
tar zxf A64_v82A_ISA_xml_00bet3.2.tar.gz
tar zxf SysReg_v82A_xml-00bet3.2.tar.gz SysReg_v82A_xml-00bet3.2
tar zxf AArch32_v82A_ISA_xml_00bet3.2.tar.gz
tar zxf ARMv82A-SysReg-00bet3.2.tar.gz
cd ..

make all


**2. $ python3 --version**
Python 3.5.2

3. CentOS Release 6.6

**Comment by alastairreid** [comment]
Thanks pariveshdev.
Can you confirm that you are using an up to date copy of the git repo?
Either do "git pull" to make it up to date or use "git log --oneline" to see which version you have checked out.

**Comment by alastairreid** [comment]
Since I can't reproduce the problem, I can't test this but one thing you might try is changing the offending line from:

     r.defs.add(m[2])

to

     r.defs.add(m.group(2))

The second way is how you used to do it in Python2.

If that gets things working, can you send me a pull request with the necessary changes?  Thanks.

**Comment by pariveshdev** [comment]
r.defs.add(m.group(2)) worked.

Thank you.

**Comment by alastairreid** [comment]
Thanks for the fix - sorry it took me so long to merge - busy week.
