### ISSUE TITLE
Stand alone slices and slice syntax

### ISSUE THREAD

**Issue by alehed** [alastairreid/mra_tools#10]
Hi,

This problem is more about the specification than the parsing tools. Is a standalone slice like in `<X, Y>` valid ASL? The specification says nothing about that case but the SHA1C instruction has pseudocode containing `<Y, X> = ROL(Y:X, 32);`. To me that seems like the person meant to write `(Y, X) = ROL(Y:X, 32);` or `Y:X = ROL(Y:X, 32);` (if concatenations are assignable).

The other problem is that the new slice syntax overlaps with the array-style function syntax. A free token that comes to my mind would be `<<<` and `>>>` or `{` and `}`.

PS: If this question is off-topic feel free to close it and/or direct me to the appropriate place to ask the question.

**Comment by alehed** [comment]
In general what is the best way to report problems with the specification? I found some 3-space indents in the pseudocode.

**Comment by alastairreid** [comment]
Yes, the "<X, Y> = e;" syntax is valid.  It is a variant of syntax like "PSTATE.<N,Z,C,V> = e;"
"(X, Y) = e;" is used if e is a tuple.  "<X, Y> = e;" is used if e is a bit vector - the bit vector is split into two parts with lengths matching the lengths of X and Y.
(What I mostly don't like about the syntax is that it is not used very much - which means that people won't easily guess what it means.)

Switching bitslice syntax from <> to [] has pros and cons.
Pros:
- fits with the idea that bit vectors are just an array of bits
- eliminates the parsing lookahead problem in "F(a<b,c,d,e ...." which can end either "F(a<b,c,d,e>)" or end "F(a<b,c,d,e)"
- its what future Arm specs will be using (not sure when the switchover will happen)
Cons:
- it adds a bit vector ambiguity to the existing array vs. function-call ambiguity
