### ISSUE TITLE
how to decode ASL

### ISSUE THREAD

**Issue by katetsu** [alastairreid/mra_tools#6]
Hi,

I have been trying to understand how to use the scripts. - mainly instr2asl.py to no avail.

I'm mainly interested in understanding and possibly converting the ASL to C or python...

for example, I have this code: - can I use the script to decode it?
```
len = HighestSetBit(immN:NOT(imms));
bits(6)` levels;
levels = ZeroExtend(Ones(len), 6);
```
Many thanks
Hoss

**Comment by alastairreid** [comment]
I have fixed the parser to work with the latest version of OCaml.
At the moment, the parser does not generate an AST and there is no type checker - but the grammar for the language is in src/parser.mly.
To test the parser, use "make test".  (See the bottom of README.md for dependencies you will need to install first.)

**Comment by katetsu** [comment]
Thanks. where should I run "make test" ?
both here:

```
~/mra_tools$ make test
make: *** No rule to make target 'test'.  Stop.
```
and here
```
~/mra_tools$ make test
make: *** No rule to make target 'test'.  Stop
```
 
have no test config defined...

Thanks a lot for your help.
Hoss
