### ISSUE TITLE
PMCEID field oddness

### ISSUE THREAD

**Issue by ratmice** [alastairreid/mra_tools#7]
After building regs.asl, PMCEID's fields look odd,

$ grep PMCEID[0-1]_EL0 regs.asl
__register 64 { 63:32 IDhi, 63:32 ID } PMCEID1_EL0;
__register 64 { 31:0 IDhi, 31:0 ID } PMCEID0_EL0;

it seems to me like this should be { 63:32 IDhi, 31:0 ID } for both,
like in the xml field_lsb and field_msb are

but the script generating regs.asl is interpreting the names "IDhi[62:32]" and "IDhi[31:0]" as bit slices,
but the name and the fields, do not appear to be in harmony.  I can imagine situations in which a simulator might not notice such an issue unless tests are interleaving changes to both fields.

Is this working as intended?

**Comment by alastairreid** [comment]
The problem seems to have been that the XML refers to the field in bitslice [31:0] as "ID[63:32]" - and I was using the info extracted from the name instead of using the bitslice location.
Fixed now.
